# Generated by Django 4.1.2 on 2022-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('muscle', models.IntegerField(choices=[(0, 'PARTIA'), (1, 'PLECY'), (2, 'BARKI'), (3, 'KLATA'), (4, 'NOGI'), (5, 'POŚLADKI'), (6, 'TRICEPS'), (7, 'BICEPS'), (8, 'BRZUCH'), (9, 'CARDIO')], default=0)),
            ],
        ),
    ]
