# Generated by Django 4.1.2 on 2022-11-02 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_exercise_image_pr'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='pr',
            field=models.PositiveIntegerField(choices=[(1, 'KG'), (2, 'KM')], default=1),
        ),
        migrations.AddField(
            model_name='pr',
            name='reps',
            field=models.IntegerField(default=0),
        ),
    ]
