# Generated by Django 4.1.2 on 2022-11-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_pr_pr_pr_reps'),
    ]

    operations = [
        migrations.AddField(
            model_name='pr',
            name='wieght',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pr',
            name='reps',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
