# Generated by Django 4.1.2 on 2022-11-11 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_pr_wieght_alter_pr_reps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pr',
            old_name='wieght',
            new_name='weight',
        ),
    ]
