# Generated by Django 4.1.2 on 2022-11-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_currentplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentplan',
            old_name='current',
            new_name='plan',
        ),
    ]
